name: Automatically update Docker image versions

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'iasuhiu3hdiuwdhiuwhqfs'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '17'

      - name: Run automation script
        run: node --experimental-fetch ./build-automation.js

      - name: Create update PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          branch: update-branch
          commit-message: "version update"
          title: "Version update"
          delete-branch: "true"
          team-reviewers: |
            owners
            maintainers







