name: Automatically update Docker image versions

on:
  # schedule:
  #   - cron: "*/15 * * * *"
  pull_request:
    types: [ synchronize, opened, reopened, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner != 'nodejs'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '17'

      - name: Run automation script
        run: node --experimental-fetch build-automation.js

      - name: Create update PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          branch: update-branch
          base: test-branch
          commit-message: "version update"
          title: "Version update"
          delete-branch: "true"
          team-reviewers: |
            owners
            maintainers

      - name: Wait 2 second
        run: sleep 2

      - name: Auto-merge PR when ready
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}






