name: Automatically update Docker image versions

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'nodejs'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          # to access `--experimental-fetch`
          node-version: '17'

      - name: Run automation script
        id: updt
        run: node --experimental-fetch build-automation.mjs

      - name: Create update PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          branch: update-branch
          base: main
          commit-message: "Update to ${{ steps.updt.outputs.updated-versions }}"
          title: "Update to ${{ steps.updt.outputs.updated-versions }}"
          delete-branch: true
          team-reviewers: |
            @nodejs/docker

      - name: Check CI status periodically
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: node --experimental-fetch check-pr-status.mjs ${{ github.repository }} ${{ steps.cpr.outputs.pull-request-number }}

      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GH_API_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      - name: Merge PR
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_API_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
