name: Automatically update Docker image versions

on:
  # schedule:
  #   - cron: "15 * * * *"
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner != 'nodejs'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Run automation script
        run: node ./build-automation.js

      - name: Create update PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          branch: update-branch
          commit-message: "version update"
          title: "Version update"
          body: |
            @LaurentGoderre @PeterDaveHello @SimenB @Starefossen @nschonni @ttshivers
          






