name: Automatically update Docker image versions

on:
  # schedule:
  #   - cron: "15 * * * *"
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner != 'nodejs'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Run automation script
        run: node ./build-automation.js





