name: Automatically update Docker image versions

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    # if the repo owner isn't nodejs and the branch isn't update-branch
    if: github.repository_owner == 'nodejs'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '17'

      - name: Run automation script
        run: node --experimental-fetch build-automation.js

      - name: Create update PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          branch: update-branch
          base: main
          commit-message: "version update"
          title: "Version update"
          delete-branch: "true"
          team-reviewers: |
            owners
            maintainers

      - uses: actions/checkout@v2

      - name: Check CI status periodically
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: node --experimental-fetch check-pr-status.js ${{ github.repository }} ${{ steps.cpr.outputs.pull-request-number }}

      - name: Merge PR
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_API_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: squash



