name: Automatically update Docker image versions

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'nodejs'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          # to access `--experimental-fetch`
          node-version: '17'

      - name: Run automation script
        run: node --experimental-fetch build-automation.mjs

      - name: Get updated versions from updated_versions file and store in env vars
        run: |
          [ -f updated_versions ] && echo "UPDATED_VERSIONS=$(cat updated_versions)" >> GITHUB_ENV
          rm -f updated_versions

      - name: Create update PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          branch: update-branch
          base: main
          commit-message: "Update to $UPDATED_VERSIONS"
          title: "Update to $UPDATED_VERSIONS"
          delete-branch: true
          team-reviewers: |
            @nodejs/docker

      - uses: actions/checkout@v2

      - name: Check CI status periodically
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: node --experimental-fetch check-pr-status.mjs ${{ github.repository }} ${{ steps.cpr.outputs.pull-request-number }}

      - name: Merge PR
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_API_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: squash
